import { createElement } from 'lwc';
<<<<<<<< HEAD:force-app/main/default/lwc/boatAddReviewForm/__tests__/boatAddReviewForm.test.js
import BoatAddReviewForm from 'c/boatAddReviewForm';

describe('c-boat-add-review-form', () => {
========
import ParentY from 'c/parentY';

describe('c-parent-y', () => {
>>>>>>>> a97fc7856975806696e2b82d5a66267ee238dccc:force-app/main/default/lwc/parentY/__tests__/parentY.test.js
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
<<<<<<<< HEAD:force-app/main/default/lwc/boatAddReviewForm/__tests__/boatAddReviewForm.test.js
        const element = createElement('c-boat-add-review-form', {
            is: BoatAddReviewForm
========
        const element = createElement('c-parent-y', {
            is: ParentY
>>>>>>>> a97fc7856975806696e2b82d5a66267ee238dccc:force-app/main/default/lwc/parentY/__tests__/parentY.test.js
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});